print("Predicting – using social and contextual clues to guess at the topic")
print("Using selective attention – paying attention to only what seems important")
print("Preparing – thinking about what one wants to communicate in advance")
print("Looking ridiculous – being willing to look foolish in order to complete the task")
print("Practicing")
print("Monitoring – correcting one’s own speech for accuracy")
print("Asking questions")
print("Taking notes")
print("Using imagery – relating new information to a visualization")
print("Finding the answer in multiple ways")
print("Using physical response – relating new information to a physical action")
print("Playing – experimenting with language")
